# Generated by Django 4.2.26 on 2025-12-01 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagefeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('image_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='imagefeed.imagepost')),
            ],
        ),
    ]
