# Generated by Django 4.2.26 on 2025-12-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagefeed', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='imagepost',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
