# Generated by Django 4.2.26 on 2025-12-16 20:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagefeed', '0003_alter_comment_options_alter_imagepost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
